#158 - Save draft requests on application close
EXXETA/trufos pull request #172
Opened 2024-12-28 14:01 UTC by vicky16898

Fixes issue https://github.com/EXXETA/trufos/issues/158

This PR ensures that unsaved changes are now saved when the application is closed.

2024-12-29 17:04 UTC, SoulKa requested changes

2024-12-29 17:04 UTC, SoulKa commented on src/main/main.ts
> +      const timeoutId = setTimeout(() => {
I would declare `timeoutId` with `let` on top of the close callback since it is actually used above its current declaration (in `handleResponse` and `cleanup`).

2024-12-29 17:04 UTC, SoulKa commented on src/main/main.ts
> +      const handleResponse = () => {
would move it directly into the `.once()`

2024-12-29 17:04 UTC, SoulKa commented on src/main/main.ts
> +      mainWindow?.webContents.send('save-before-close');
`save-before-close` can be generalized to `before-close` so we can use this event for other purposes in the future, too.

2024-12-29 17:04 UTC, SoulKa commented on src/main/main.ts
> +  mainWindow.on('close', async (event) => {
In summary, I would adjust the code inside `if` to some thing like

```ts
      isQuitting = true;
      event.preventDefault();
      mainWindow?.webContents.send('save-before-close');
      
      await Promise.race([
        once(ipcMain, 'save-before-close-response'),
        new Promise((resolve) => setTimeout(resolve, 5000)),
      ]);
```

This prevents the declaration of the helper methods inside this callback and has a more linear code flow.

2024-12-29 17:04 UTC, SoulKa commented on src/renderer/view/MainWindow.tsx
> +        updateRequest(await eventService.saveChanges(draftRequest), true);
`saveChanges()` should not be called, as this overrides the currently saved request with the draft content. On application close, the unsaved changes (if any) of the *currently selected request* should be saved as draft. This is the same behavior as implemented on request selection change: https://github.com/EXXETA/trufos/blob/main/src/renderer/state/requestStore.ts#L136

In general, we do not want any business logic in components/tsx files. We want to separate frontend/components and logic as much as possible. I suggest moving the event handling into a new file under `src/renderer/services/event`. This PR will likely not need to change any `.tsx` file.

2024-12-31 18:46 UTC, vicky16898 commented on src/renderer/view/MainWindow.tsx
> +        updateRequest(await eventService.saveChanges(draftRequest), true);
Can the existing renderer-event-service.ts be used or should I create a new event file?

2025-01-01 16:37 UTC, SoulKa commented on src/renderer/view/MainWindow.tsx
> +        updateRequest(await eventService.saveChanges(draftRequest), true);
I think it's cleaner to create a new file for that in the same directory.

2025-01-28 08:17 UTC, SoulKa commented
Hi @vicky16898, haven't heard from you for a while, so I opened another PR which will replace this one. You're still author of your changed lines in it.

See #210

2025-01-28 08:17 UTC, closed without merging